/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fangsheng_myapplication_jnidemo_JniDemoActivity */

#ifndef _Included_com_example_fangsheng_myapplication_jnidemo_JniDemoActivity
#define _Included_com_example_fangsheng_myapplication_jnidemo_JniDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fangsheng_myapplication_jnidemo_JniDemoActivity
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fangsheng_myapplication_jnidemo_JniDemoActivity_helloJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
